CREATE DATABASE QueriesDB;

USE QueriesDB;

CREATE TABLE FAQ (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Query VARCHAR(255) NOT NULL,
    Reply TEXT NOT NULL
);

INSERT INTO FAQ (Query, Reply)
VALUES 
('How can I book an Airbnb?', 'You can book an Airbnb by searching for a property, selecting your dates, and following the booking process on the website.'),
('Can I cancel my booking?', 'Yes, you can cancel your booking, but it depends on the cancellation policy of the property you booked.'),
('How do I contact the host?', 'You can contact the host through the Airbnb messaging system once your booking is confirmed.'),
('What payment methods are accepted?', 'Airbnb accepts various payment methods including credit/debit cards, PayPal, and other local payment options depending on your location.'),
('Can I get a refund?', 'Refunds depend on the cancellation policy of the property you booked. Please check the policy before canceling.'),
('How do I leave a review?', 'You can leave a review after your stay by visiting the "Trips" section and selecting the booking to review.'),
('Is there a service fee for booking?', 'Yes, Airbnb charges a service fee which is included in your total booking cost.'),
('How do I find pet-friendly properties?', 'Use the filters in the search section to find pet-friendly properties.'),
('Can I book for someone else?', 'Yes, you can book for someone else by entering their information during the booking process.'),
('What happens if the host cancels my booking?', 'If the host cancels, you will receive a full refund or assistance in booking a similar property.'),
('Are there any discounts for long-term stays?', 'Some hosts offer discounts for long-term stays. You can check the listing details for more information.'),
('How can I verify my identity?', 'You can verify your identity through the account settings by providing a government-issued ID.'),
('What are the check-in and check-out times?', 'Check-in and check-out times vary by property. Please check the listing details for specific times.'),
('Can I change my booking dates?', 'Yes, you can request to change your booking dates by contacting the host. Approval depends on their availability and policies.'),
('How do I get a receipt for my booking?', 'You can download your receipt from the "Trips" section under your booking details.'),
('Is Wi-Fi available in the property?', 'Wi-Fi availability depends on the property. Please check the amenities section of the listing.'),
('Are there any extra charges?', 'Extra charges such as cleaning fees or additional guest fees may apply. Please review the listing details.'),
('How do I report a problem during my stay?', 'You can report a problem by contacting Airbnb support or through the app under your booking details.'),
('Can I host on Airbnb?', 'Yes, you can host on Airbnb by creating a listing and following the hosting guidelines.'),
('How do I edit my profile?', 'You can edit your profile in the account settings section of the Airbnb website.'),
('Is Airbnb safe to use?', 'Airbnb has safety measures in place, including secure payments and verified reviews, to ensure a safe experience.'),
('What should I do if I can’t find my booking?', 'If you can’t find your booking, check your email for confirmation or visit the "Trips" section in your account.'),
('Can I request an early check-in?', 'You can request an early check-in by messaging the host, but approval depends on their schedule.'),
('How do I use a coupon or discount code?', 'You can apply a coupon or discount code during the payment process before completing your booking.'),
('What is the guest limit for a property?', 'The guest limit varies by property. Please check the listing details for the maximum number of guests allowed.'),
('Can I book without a verified profile?', 'Some hosts require guests to have a verified profile. It\'s recommended to verify your profile for a smoother booking process.'),
('What if I forget something at the property?', 'Contact the host through the Airbnb messaging system to arrange retrieval of your forgotten items.'),
('How do I change my payment method?', 'You can change your payment method in the payment section during the booking process.'),
('What is the difference between Instant Book and Request to Book?', 'Instant Book allows immediate booking without host approval, while Request to Book requires the host\'s approval.'),
('Are there any accessibility options?', 'Yes, you can use the accessibility filters to find properties suitable for guests with disabilities.'),
('How do I add a profile photo?', 'You can add a profile photo in the account settings section of your Airbnb account.'),
('Can I share a wishlist?', 'Yes, you can share your wishlist with friends or family through the sharing options in the app.'),
('How do I apply to become a Superhost?', 'Superhost status is awarded based on hosting performance and reviews. No application is needed, but maintaining excellent service is key.'),
('Can I get travel insurance for my booking?', 'Airbnb offers travel insurance options through third-party providers. Check the "Travel Insurance" section for more details.'),
('How do I use the map feature?', 'The map feature is available in the search section to help you locate properties in specific areas.'),
('What if the property is not as described?', 'Contact Airbnb support immediately if the property is not as described to resolve the issue.'),
('How do I enable notifications?', 'You can enable notifications in the app settings to stay updated on your bookings and messages.'),
('Can I list multiple properties?', 'Yes, you can list multiple properties on Airbnb.'),
('What is the Airbnb cleaning protocol?', 'Airbnb has enhanced cleaning protocols that hosts are encouraged to follow to ensure guest safety.'),
('How do I search for properties with a pool?', 'Use the "Pool" filter in the amenities section during your search to find properties with a pool.'),
('Can I save properties for later?', 'Yes, you can save properties to your wishlist to view them later.'),
('What happens if the property is double-booked?', 'If a property is double-booked, Airbnb support will help you find alternative accommodation or offer a refund.'),
('How do I check if a property is available?', 'Check the calendar on the listing page to see the availability of the property.'),
('Can I book last-minute stays?', 'Yes, many properties allow last-minute bookings. Use the "Instant Book" filter for faster booking options.'),
('What is the Airbnb resolution center?', 'The Airbnb resolution center helps resolve issues between hosts and guests, such as refunds or reimbursements.'),
('How do I find properties with a kitchen?', 'Use the "Kitchen" filter in the amenities section to find properties with a kitchen.'),
('Can I message a host before booking?', 'Yes, you can message the host to ask questions before booking by clicking "Contact Host" on the listing page.'),
('How do I know if a property is child-friendly?', 'Check the amenities section or contact the host to confirm if the property is suitable for children.'),
('What should I do if I have allergies?', 'Contact the host before booking to discuss your allergies and ensure the property is suitable for you.'),
('Can I extend my stay after check-in?', 'You can request to extend your stay by messaging the host, but it depends on the property\'s availability.'),
('How do I find listings with free cancellation?', 'Use the "Free cancellation" filter in the search options to find listings with flexible cancellation policies.'),
('What is the Airbnb Experiences feature?', 'Airbnb Experiences are unique activities hosted by local experts, offering a deeper connection to the places you visit.'),
('Can I split the payment with friends?', 'Currently, Airbnb does not offer a split payment feature, but you can coordinate with your friends to share the costs.'),
('How do I become a host?', 'You can become a host by clicking "Become a Host" on the Airbnb website and following the steps to create your listing.'),
('What is the Airbnb Plus program?', 'Airbnb Plus features verified homes that meet high standards of quality, comfort, and design.'),
('Can I find properties suitable for remote work?', 'Yes, use the "Dedicated workspace" filter to find properties with suitable spaces for remote work.'),
('How do I use Airbnb gift cards?', 'You can redeem Airbnb gift cards during the checkout process by entering the code in the payment section.'),
('What if the host is unresponsive?', 'If the host is unresponsive, you can contact Airbnb support for assistance.'),
('How do I change my booking details after confirmation?', 'You can request changes to your booking by contacting the host through the Airbnb messaging system.'),
('What are the Airbnb Luxe properties?', 'Airbnb Luxe offers high-end, luxurious properties with dedicated trip designers to plan your stay.'),
('How can I get the best price for a booking?', 'Book early, use filters to find discounts, and consider longer stays for potential savings.'),
('Can I list a shared room on Airbnb?', 'Yes, you can list shared rooms, but make sure to clearly describe the space and amenities offered.'),
('How do I check the safety features of a listing?', 'Check the "Safety features" section of the listing or contact the host for more information'),
('Can I filter properties by smoking policy?', 'Yes, use the filters to find properties that match your smoking preferences, either smoking allowed or non-smoking.'),
('What are Airbnb’s COVID-19 policies?', 'Airbnb has implemented enhanced cleaning protocols and flexible booking options during the COVID-19 pandemic.'),
('How do I find properties with air conditioning?', 'Use the "Air conditioning" filter in the amenities section to find properties with this feature.'),
('Can I message multiple hosts at once?', 'No, you can only message hosts individually, but you can contact different hosts for different properties.'),
('What if I find a cheaper listing after booking?', 'Airbnb does not offer price matching, so it’s best to book when you are sure of the price and dates.'),
('How do I find unique stays like tree houses or castles?', 'Use the "Unique stays" filter in the search options to find distinctive accommodations.'),
('Can I see the guest reviews before booking?', 'Yes, guest reviews are available on each listing page, providing insights from previous visitors.'),
('What is the difference between Superhost and regular hosts?', 'Superhosts are experienced hosts with high ratings, providing excellent service to guests.'),
('Can I request a custom itinerary for my stay?', 'While Airbnb doesn’t offer custom itineraries, you can discuss your needs with the host or book Airbnb Experiences for local activities.'),
('How do I delete my Airbnb account?', 'You can delete your account in the account settings under "Privacy and Sharing."'),
('Are there properties with hot tubs available?', 'Yes, you can find properties with hot tubs by using the "Hot tub" filter in the amenities section.'),
('Can I book a property for a group event?', 'Yes, but it’s essential to discuss your plans with the host to ensure the property is suitable for events.'),
('How do I find properties with a balcony or terrace?', 'Use the "Balcony" or "Terrace" filter in the amenities section to find such properties.'),
('What is Airbnb’s policy on party houses?', 'Airbnb prohibits party houses and has policies in place to prevent disruptive events.'),
('Can I book an Airbnb without a credit card?', 'Yes, depending on your location, Airbnb accepts other payment methods like PayPal or local payment options.'),
('How do I reset my Airbnb password?', 'You can reset your password by clicking "Forgot password?" on the login page and following the instructions.'),
('Can I get an invoice with a company name for my booking?', 'Yes, you can request an invoice with a company name during the booking process under the billing information.'),
('Are there properties with gyms available?', 'Yes, use the "Gym" filter in the amenities section to find properties with fitness facilities.'),
('How do I report a listing that violates Airbnb policies?', 'You can report a listing by clicking "Report" on the listing page and following the instructions.'),
('Can I use Airbnb for a short-term rental of a few hours?', 'Airbnb typically requires bookings for at least one night, but you can check with the host for any exceptions.'),
('How do I save a search on Airbnb?', 'You can save a search by clicking the "Save" button on the search results page.'),
('What happens if I accidentally book the wrong dates?', 'Contact the host immediately to request a date change or contact Airbnb support for assistance.'),
('Can I find properties with electric vehicle chargers?', 'Yes, use the "EV charger" filter in the amenities section to find properties with this feature.'),
('What is Airbnb’s policy on pets?', 'Pet policies vary by property. Use the "Pets allowed" filter to find pet-friendly accommodations.'),
('How do I know if a host is trustworthy?', 'Trustworthy hosts often have good reviews, verified profiles, and prompt communication.'),
('Can I use Airbnb for long-term rentals?', 'Yes, Airbnb offers long-term rentals, and you can find them by selecting extended stay options in the search filters.'),
('What if I feel unsafe during my stay?', 'Contact Airbnb support immediately for assistance if you feel unsafe during your stay.'),
('How do I apply for a refund due to extenuating circumstances?', 'Apply for a refund through the resolution center by providing the necessary documentation for your case.'),
('Can I book an Airbnb as a gift for someone else?', 'Yes, you can book an Airbnb for someone else by entering their information during the booking process.'),
('Are there properties with wheelchair access?', 'Yes, use the "Wheelchair accessible" filter to find properties suitable for guests with mobility challenges.'),
('How do I set a budget for my search?', 'You can set a budget by adjusting the price range slider in the search filters.'),
('What is the Airbnb Host Guarantee?', 'The Airbnb Host Guarantee provides protection for hosts in case of property damage by guests, up to a certain limit.'),
('How do I cancel a reservation made with a coupon?', 'You can cancel the reservation through the "Trips" section, and the coupon will be reissued if eligible.'),
('Can I book properties with laundry facilities?', 'Yes, use the "Washer" or "Dryer" filters to find properties with laundry facilities.'),
('Can I extend a trip that has already ended?', 'You cannot extend a trip that has ended, but you can make a new booking for additional nights.'),
('What if I arrive late at the property?', 'Inform the host about your late arrival to ensure they are aware and can accommodate you.'),
('How do I find properties with a fireplace?', 'Use the "Fireplace" filter in the amenities section to find properties with a fireplace.');